                /////*This code is generated by Di2Code team*/////
#pragma once
#include <string>
using namespace std;

class Person
{
private: 
  //write your private attributes here
public:
   string Name = "";

   void  S2ETD();
   Person();
   ~Person();
};


