                /////*This code is generated by Di2Code team*/////
#include "cpp_code.h"

void  S2ETD()
{
    //write your funtion implementation here
    return ;
}
Person::Person()
{
    //write your constructor implementation here
}
Person::~Person()
{
    //write your destructor implementation here
}


void enroll()
{
    //write your funtion implementation here
    return ;
}
student::student()
{
    //write your constructor implementation here
}
student::~student()
{
    //write your destructor implementation here
}


