                #####This code is generated by Di2Code team#####
class Person():
   def __init__(self):
       self.Name = ""

   def  S2ETD(self):
       # write your funtion implementation here
       # please note that the return value is void
       pass

class student():
   def __init__(self):
       self.Class = 0

   def  enroll(self):
       # write your funtion implementation here
       # please note that the return value is void
       pass

