                #####This code is generated by Di2Code team#####
class Person:
   def __init__(self):
       self.age = 0

   def  get_age(self):
       # write your funtion implementation here
       # please note that the return value is int
       pass

class Student(Person):
   def __init__(self):
       self.id = ""

   def  get_gpa(self):
       # write your funtion implementation here
       # please note that the return value is float
       pass

class Professor(Person):
   def __init__(self):
       self.title = ""

   def  teach(self):
       # write your funtion implementation here
       # please note that the return value is void
       pass

